# configs
CC = gcc
COMPILER_FLAGS = -Wall -O3
LINKER_FLAGS = -lm

# alvos de compilacao
all: testlechong

testlechong: testlechong.c
	$(CC) testlechong.c $(COMPILER_FLAGS) $(LINKER_FLAGS) $(CFLAGS) -o lechong

