# targets de compilacao
all: mcalc cloudz

# programa extrator de momentos invariantes
mcalc: mcalc.c
	gcc mcalc.c -lm -Wall -o ../bin/mcalc

# utilitario manipulador de nuvens via linha de comando
cloudz: cloudz.c
	gcc cloudz.c -lm -Wall -o ../bin/cloudz
