all: char-ext cloudview centerprofile

char-ext: char-ext.c
	gcc char-ext.c -o ../bin/char-ext -lm
	
cloudview: cloudview.c
	gcc cloudview.c -o ../bin/cloudview -lm -lGL -lGLU -lglut
	
centerprofile: centerprofile.c
	gcc centerprofile.c -o ../bin/centerprofile -lm
	
